### ISSUE TITLE
Dodge Plugin

### ISSUE THREAD

**Issue by DoisPontinhos** [sl-miguel/ExileX#1]
Hey, would love to see a dodge plugin

**Comment by sl-miguel** [comment]
Sorry, but exile only interacts with the LCU API, so a dodge plugin isn't doable.
However, you might want to check out [ayaya-league-external](https://github.com/botkalista/ayaya-league-external)

**Comment by DoisPontinhos** [comment]
I would also like to add a bug where you have "Report Message" in Auto Honor with someones IGN

**Comment by sl-miguel** [comment]
Originally, it was tailored to honor a specific friend, but I've adjusted it to be more user-friendly
